---
title: "About"
output: postcards::trestles
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# install.packages("postcards")
library(postcards)
```

```{css}
a {
    color: #E57248;
}

a:hover {
    color: white;
    background-color: #E57248;
}
```

## Research interests 

**Keywords: decision making, risk preference, safety perception, lifespan development, virtual reality, cognitive neuroscience, measurement, legal decision making**

<p style="text-align:justify;">My research focuses on decision making under uncertainty, with a particular interest in risk preference, safety perception, and lifespan development. I investigate how people perceive and respond to risk, how these processes change across the lifespan, and how different approaches to measuring decision making converge. I am also interested in the neural mechanisms underlying individual differences in decision making and their implications for real-world and legal contexts.</p>

<p style="text-align:justify;">To address these questions, I combine behavioural experiments, surveys, neuroimaging, and virtual reality with rigorous quantitative methods. My long-term goal is to translate insights from decision science into legal settings, including research on crime, safety, and justice.</p>\


## Positions
* 01/2026 - present: Senior researcher, Center for Cognitive and Decision Sciences, University of Basel, Switzerland
* 10/2025: Visiting researcher at the Max Planck Institute for the Study of Crime, Security and Law (Freiburg im Breisgau, Germany); [Quickfire Q&A](https://www.youtube.com/watch?v=RaGMnsBxwKk&t=47s)
* 05/2021 - 12/2025: Postdoctoral research assistant, Center for Cognitive and Decision Sciences, University of Basel, Switzerland
* 11/2019 - 04/2021: Postdoctoral research fellow, spanlab, Stanford University, CA, USA
* 07/2018 - 09/2019: Postdoctoral research assistant, Center for Cognitive and Decision Sciences, University of Basel, Switzerland\


## Education 
* 09/2014 - 06/2018: PhD Psychology, Center for Cognitive and Decision Sciences, University of Basel, Switzerland
* 10/2012 - 09/2014: MSc Social, Cognitive, and Affective Neuroscience, Free University Berlin, Berlin, Germany
* 09/2011 - 11/2012: MRes Security Science, University College London, UK
* 10/2008 - 11/2009: MSc Crime Science, University College London, UK
* 10/2005 - 08/2008: BSc (Hons) Psychology, Goldsmiths' College, University of London, UK\


## Grants and awards
* 2025: Seed Money project funding from Eucor – The European Campus, co-applicant Dr. Rebecca Albrecht (Albert Ludwig University of Freiburg, Germany)
* 2025: Postdoctoral fellowship scholarship, Max Planck Institute for the Study of Crime, Security and Law (Freiburg im Breisgau, Germany)
* 2025: Research grant from the Biäsch Foundation
* 2025: Research grant from the Freiwillige Akademische Gesellschaft Basel
* 2024: Steven Karger Prize from the Faculty of Psychology, University of Basel; [Interview with Karger Publishers](https://www.youtube.com/watch?v=isDf9Ha6boA)
* 2024: University of Basel Research Fund for Excellent Junior Researchers
* 2023: Open Data Award from the Scientific Research Network On Decision Neuroscience & Aging
* 2023: Cross-Border Education Grant (with Dr. Dorothée Bentz and Prof. Dr. Tara Donker)
* 2019: Early Postdoc.Mobility Grant from the Swiss National Science Foundation
* 2018: University of Basel Research Fund for Excellent Junior Researchers
* 2015: Student Travel Award to attend and present poster at the Scientific Research Network on Decision Neuroscience and Aging conference, Miami, FL.
* 2009: Penny Willow Prize for best MSc dissertation in Crime Science in 2009, Jill Dando Institute for Crime Science, University College London\


## Science communication
* 2026: Radio interview on gender differences in risk taking; [Interview with Bayerischer Rundfunk](https://www.br.de/nachrichten/bayern/badetote-meist-maennlich-warum-maenner-oft-risikobereiter-sind,VOCt2BL)
* 2026: Public lecture "Risiko im Kopf: Einblicke in die Entscheidungsfindung aus Sicht der Gehirnforschung"; [Woche des Gehirns](https://neuronetwork.unibas.ch/en/das-hirn-erforschen/woche-des-gehirns-2026/)
* 2023: Participation in *Rendez-vous*, organized by Science et Cité and Reatch 
* 2022 - 2023: Organization Committee of [Methods4Postdocs](https://psychologie.unibas.ch/de/methods-training-for-postdocs/)
* 2022: Organization Committee of [BEACON](https://psychologie.unibas.ch/de/beacon/)\


## Peer review activities
I have written reviews for several journals, including _Psychological Science, Journal of Personality and Social Psychology: Personality Processes and Individual Differences, PLoS One, Psychology and Aging, Scientific Reports, Journal of Experimental Psychology: General, Gerontology, Experimental and Clinical Psychopharmacology, npj Science of Learning, Thinking & Reasoning, Cognitive Psychology, Cognition and Emotion, Psychophysiology, Human Brain Mapping, Developmental Psychology, Frontiers in Psychology, International Journal of Behavioral Development, Journal of Behavioral Decision Making, Journal of Cognitive Psychology, Journal of Gerontology: Psychological Sciences, Value in Health._ For a verified list of the most recent reviews, please visit my profile on [Publons](https://publons.com/researcher/4347373/loreen-tisdall/). I am also a regular reviewer for the [Ethics Committee of the Faculty of Psychology, University of Basel](https://psychologie.unibas.ch/de/forschung/governance/ethikkommission-der-fakultaet-fuer-psychologie/#c43724).  

