---
title: "Negotiation seminar"
output:
  postcards::trestles
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# install.packages("postcards")
library(postcards)
```

## Course summary
<p style="text-align:justify;">The idea that some people are born negotiators who employ the _art of negotiation_ to achieve maximally beneficial results for their own purpose is a pervasive one, yet it is scientifically questionable. Instead, there may be much more of a _science of negotiation_, which can help individuals to prepare for, engage in, and close negotiations, and to do so more successfully. Negotiations are complex, of course, with outcomes ranging from getting the purchase price down on a new bike, to deciding the future of company employees during a takeover, or ending a hostage situation peacefully and without injury. By examining negotiations scientifically, we can establish basic principles that hold across different negotiation situations, which in turn allow us to identify factors that influence negotiation processes and outcomes. </p>

## Aim of the course
<p style="text-align:justify;">This seminar is aimed at Master students, who will learn the fundamental principles and concepts underlying negotiation theory and behavioral decision making. Based on concrete role-playing exercises featuring predefined goals, budgets, etc., students will develop and continually improve their negotiation skills, including how to frame, prepare, and conduct different kinds of negotiations.</p>

## Background literature
+ [Raiffa, H. E., Richardson, J., & Metcalfe, D. (2007). _Negotiation analysis: The science and art of collaborative decision making._ Cambridge: Harvard University Press.](https://books.google.ch/books?hl=en&lr=&id=e2n9DwAAQBAJ&oi=fnd&pg=PT6&dq=Negotiation+analysis:+The+science+and+art+of+collaborative+decision+making&ots=40nVUGafcp&sig=JZVpC8mogdIkLAgD6U9jlikbEdU&redir_esc=y#v=onepage&q=Negotiation%20analysis%3A%20The%20science%20and%20art%20of%20collaborative%20decision%20making&f=false)
+ [Malhotra, D. & Bazerman, M.H. (2007). _Negotiation genius._ New York: Dell.]((https://books.google.ch/books?hl=en&lr=&id=ChWCIeUW3CEC&oi=fnd&pg=PA1&dq=Negotiation+Genius:+How+to+Overcome+Obstacles+and+Achieve+Brilliant+Results+at+the+Bargaining+Table+and+Beyond&ots=wQpnbOt7bA&sig=qdq_MKoxoUQDA_hnm_4QGMoZlj4&redir_esc=y#v=onepage&q=Negotiation%20Genius%3A%20How%20to%20Overcome%20Obstacles%20and%20Achieve%20Brilliant%20Results%20at%20the%20Bargaining%20Table%20and%20Beyond&f=false))
+ [Fisher, R., & Ury, W. (1981). _Getting to yes._ New York, USA: Penguin.](https://www.cdowcym.org/documents/resources/gettingtoyes.pdf)
+ Session-specific readings will be announced as required.

## Prerequisites
None.

## Sessions Spring Semester 2023
The Negotiation seminar in FS23 takes place on Tuesdays, 2:15pm-3:45pm (GMT+1).


|  WEEK   |    DATE     | TOPIC                                                               | NOTE             | 
| :------:| ---------   | ------------------------------------------------------------------- | ---------------- | 
| 1       | 21.02.23    | **Course overview & introduction**                                  |                  | 
| 2       | 28.02.23    | Fasnacht                                                            | *No seminar*     |             
| 3       | 07.03.23    | **Negotiation theory I**                                              
|         |             | + Raiffa et al. (2007), Chapters 1-4.                               |                  |
| 4       | 14.03.23    | **Negotiation theory II**                                                    
|         |             | + Raiffa et al. (2007), Chapters 1-4.                               |                  |
| 5       | 21.03.23    | **Preparing for negotiation: BATNA, ZOPA, RV, TV**                  
|         |             | + Malhotra & Bazerman (2007), Chapters 1-2.                         
|         |             | + Raiffa et al. (2007), Chapter 7.                                  |                  |
| 6       | 28.03.23    | **Distributive negotiation: Exercise**                              
|         |             | + Raiffa et al. (2007). Chapters 6-7.                               |                  |
| 7       | 04.04.23    | **Integrative negotiation: Exercise**                               
|         |             | + Malhotra & Bazerman (2007). Chapters 2-3.
|         |             | + Raiffa et al. (2007). Chapters 11-14.                             |                  |
| 8       | 11.04.23    | **Negotiator cognition**                                            
|         |             | + Malhotra & Bazerman (2007). Chapters 4-6.                         |                  |
| 9       | 18.04.23    | **Real world negotiation: influence, ethics, lies, & power**        
|         |             | + Malhotra & Bazerman (2007). Chapters 7-13.                        
|         |             | + Raiffa et al. (2007). Chapters 15-16.                             |                  | 
| 10      | 25.04.23    | **Distributive & integrative negotiation: Exercise**                
|         |             | + Malhotra & Bazerman (2007), Chapters 1-2.  
|         |             | + Raiffa et al. (2007). Chapters 6-7, 11-14.                        |                  |
| 11      | 02.05.23    | **Negotiating via agents: Intro & Exercise**                        
|         |             | + Malhotra & Bazerman (2007). Chapter 10.
|         |             | + Raiffa et al. (2007). Chapters 11-14.                             |                  |
| 12      | 09.05.23    | **Multi-party negotiation: Intro & Exercise**                       
|         |             | + Raiffa et al. (2007). Chapter 21.                                 |                  |
| 13      | 16.05.23    | **Preparation videocasts and group presentations**                  | *Asynchronus*    |            
| 14      | 23.05.23    | **Group presentations**                                             |                  | 
| 15      | 30.05.23    | **Wrap up and Q&A theory paper**                                    |                  |

                      






