---
title: "Projects"
output:
  postcards::trestles
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# install.packages("postcards")
library(postcards)
```

```{css}
a {
    color: #E57248;
}

a:hover {
    color: white;
    background-color: #E57248;
}
```


### Ongoing

* **Helping at a Cost** 
  + <p style="text-align:justify;">Prosocial behavior often involves personal risks, such as intervening in harassment or participating in organ donation. Research shows prosocial behavior often increases with age, yet older adults are generally more risk-averse, particularly in uncertain situations. However, little is known about how individual factors (e.g., age, gender) and societal influences (e.g., norms, wealth, hardship) shape these decisions. This project aims to fill these gaps by (1) studying the impact of individual and societal factors on personal risk decisions and their underlying mechanisms, and (2) exploring virtual reality simulations to better assess these behaviors. Key collaborator is [Kendra Seaman](https://profiles.utdallas.edu/kendra.seaman).</p>
* **Delphi-Based Agenda Setting for Extended Reality Research in Clinical and Legal Fields** 
  + <p style="text-align:justify;">Extended reality (XR), including augmented and virtual reality, is a transformative tool in clinical and legal fields, supporting therapy, training, courtroom simulations, and witness preparation. However, XR research in both domains lacks a unified agenda to address ethical, practical, and methodological challenges. This project uses a Delphi design, engaging stakeholders like researchers and policymakers, to identify and prioritize key research areas and applications, guiding ethical and impactful future advancements. Key collaborator is [Dorothée Bentz](https://psychologie.unibas.ch/de/personen/dorothee-bentz/).</p>
* **VRrisk / VRimpulsivity** 
  + <p style="text-align:justify;">In this project we are conducting a comprehensive literature search and scoping review to characterize the use of virtual reality methods in the context of risk preference and impulsivity research. Our aim is to identify common approaches, emerging challenges, and promising areas where novel technologies such as virtual reality can advance research. [__Preregistration for risk__](https://osf.io/qvsx3) and [__preregistration for impulsivity__](https://osf.io/kjd9g).</p>
* **DiffEat** 
  + <p style="text-align:justify;">In this project we are investigating the neural structural underpinnings of (disinhibited/emotional) food intake and control based on prior work suggesting specific brain tracts associated with the human reward circuitry as neural corrrelates of individual differences in impulsivity. Key collaborators are [Kelly MacNiven](https://psychology.stanford.edu/people/kelly-macniven), [Brian Knutson](https://stanford.edu/~knutson/) and [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/). [__Preregistration__](https://aspredicted.org/8kp8-dnbt.pdf)</p>
* **Classification of hormone development trajectories and link to externalizing behavior and disorder**
  + <p style="text-align:justify;">In this project we are exploring sex hormone development in early adolescence and its predictive value for externalizing behaviors. We will use longitudinal data from the Adolescence Brain and Cognitive Development (ABCD) study. Our project aims to 1) investigate if we can identify distinct classes of hormone trajectories for three sex hormones, 2) investigate the predictive validity of hormone trajectories for externalizing behaviour, and 3) assess the mediating role of impulsivity considering its central role in externalizing throughout childhood and adolescence. [__Preregistration__](https://aspredicted.org/45km-7gnq.pdf)</p>
* **Hormones, conduct disorder, and callous-unemotional traits** 
  + <p style="text-align:justify;">In this project we are conducting a systematic review and meta-analysis of the association between hormones and callous-unemotional traits as well as conduct disorder in children and adolescents. Key collaborator is [Dorothée Bentz](https://psychologie.unibas.ch/de/personen/dorothee-bentz/). [__Preregistration__](https://www.crd.york.ac.uk/prospero/display_record.php?RecordID=428686)</p>
* **The antisocial brain** 
  + <p style="text-align:justify;">In this project we are conducting a systematic review and meta-analysis of the association between human brain structure and antisocial behaviors and disorders in children, adolescents, and adults. [__Preregistration__](https://www.crd.york.ac.uk/prospero/display_record.php?RecordID=426081)</p>


### Completed 
* **DiffRisk** 
  + <p style="text-align:justify;">Previous work suggested that neural functional activity in the nucleus accumbens to risk- and reward-related cues can predict real-life risk-taking behavior. Given that nucleus accumbens functional activity is driven by neurotransmission from connected brain regions, in this project we are investigating whether the structural properties of tracts carrying signals to the nucleus accumbens may also predict risk preference. Key collaborators are [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), [Renato Frey](https://renatofrey.net), [Kelly MacNiven](https://psychology.stanford.edu/people/kelly-macniven), and [Brian Knutson](https://stanford.edu/~knutson/). [__Preprint__](https://osf.io/ab4vr/)</p>
* **AgeRisk 2.0** 
  + <p style="text-align:justify;">In this project we are investigating the effect of age on individual differences in risk preference and related constructs (impulsivity and self-control) in a healthy human life span sample. A particular focus of this project is to examine the extent to which associations between age and the different constructs differ as a function of whether we use self reports, behavioral measures, informant reports, or neuroimaging to assess risk preference, impulsivity, or self-control. Key collaborators are [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), [Renato Frey](https://renatofrey.net), [Dirk Wulff](https://www.dirkwulff.org), and [David Kellen](https://thecollege.syr.edu/people/faculty/kellen-phd-david/). [__Paper__](https://doi.org/10.1093/geronb/gbae092)</p>
* **AgeUncertainty** (2023) 
  + <p style="text-align:justify;">In this project we investigated the effect of age on neural correlates of decision-making under uncertainty. We were particularly interested in examining common and unique effects of age on the neural correlates of different kinds of uncertainty, namely paradigms of risk and temporal discounting. The key collaborator is [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/). [**Paper**](https://doi.org/10.3758/s13415-022-01060-6)</p>
* **DiffRelapse** (2020-2022)
  + <p style="text-align:justify;">I started this exciting new area of research during my time as a postdoctoral researcher at [spanlab](https://spanlab.stanford.edu) (Stanford University). In this particular project we investigated whether the structural properties of white-matter projections converging on the nucleus accumbens predict relapse to stimulant use in human stimulant use disorder patients. Key collaborators are [Kelly MacNiven](https://psychology.stanford.edu/people/kelly-macniven), [Brian Knutson](https://stanford.edu/~knutson/), [Josiah Leong](https://fulbright.uark.edu/departments/psychological-science/people/index/uid/josiah/name/Josiah+Leong/), and [Claudia Padula](https://med.stanford.edu/bravelab/about.html). [**Paper**](https://www.pnas.org/doi/10.1073/pnas.2116703119)</p>
* **Basel-Berlin Risk Study (Neuroimaging component)** (2014-2020)
  + <p style="text-align:justify;">In this project we used functional neuroimaging to investigate whether risk-taking related brain activation in two popular behavioral risk-taking measures converge at the level of the group and the individual. We also investigated whether individual differences in risk-taking related brain activity can predict actual risk-taking behavior. [**Paper**](https://www.frontiersin.org/articles/10.3389/fnbeh.2020.587152/full)</p>
* **Neuroimaging Analysis Replication and Prediction Study (narps)** (2018-2020)
  + <p style="text-align:justify;">The [narps project](https://www.narps.info/about.html) was a many-analysts study with the goal to estimate the variability of neuroscientific results coming from data collected using functional magnetic resonance imaging. [Laura Fontanesi](https://ch.linkedin.com/in/laura-fontanesi) and I contributed to this study as one of the many analysis teams. [**Paper**](https://www.nature.com/articles/s41586-020-2314-9?fbclid=IwAR3jkR1Gkraxbig5vbUz0d0_bVOTCzAFGoCmnRQMG5jpcDwiApCjxZHNHrQ)</p>
* **AgeRisk 1.0** (2015-2016)
  + <p style="text-align:justify;">In this project we investigated the convergent validity of different self-report and behavioral assessments of risk taking in a comprehensive life span sample. We also investigated whether the age-related patterns we observed for self-reported risk-taking in our study sample were representative of patterns reported for large-sale, population-based surveys. [**Paper**](https://www.researchgate.net/profile/Loreen-Tisdall/publication/308760553_Risk_Taking_Across_the_Life_Span_A_Comparison_of_Self-Report_and_Behavioral_Measures_of_Risk_Taking/links/606ad0f4a6fdccad3f71a8d3/Risk-Taking-Across-the-Life-Span-A-Comparison-of-Self-Report-and-Behavioral-Measures-of-Risk-Taking.pdf)</p>