---
title: "Publications"
output:
  postcards::trestles
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# install.packages("postcards")
library(postcards)
```

For an automated list of my publications and further information, see my **[Google Scholar profile](https://scholar.google.co.uk/citations?hl=en&user=o8ce3OwAAAAJ)**. Publications before 2017 appear under my maiden name Mamerow.

## Manuscripts submitted for peer review
<p style="text-align:justify;">
+ Tisdall, L., MacNiven, K. H., Leong, J. K., Frey, R., Rieskamp, J., Hertwig, R., Knutson, B., & Mata, R. *(under review)*. Structure of connections to the nucleus accumbens link to specific but not general measures of human risk preference. *[Preprint](https://osf.io/ab4vr/).* 
+ Tisdall, L., Frey, R., Wulff, D.U., Kellen, D., & Mata, R. *(under review)*. Lifespan trajectories of risk preference, impulsivity, and self-control: A multiverse analysis. *[Preprint](https://doi.org/10.31219/osf.io/uj359)* 
+ Bagaïni, A., Liu, Y., Kapoor, M., Son, G., Brückner, P.-C., Tisdall, L., & Mata, R. *(under review)*. Comparing the Temporal Stability and Convergent Validity of Risk Preference Measures: A Meta-Analytic Approach. *[Preprint](https://osf.io/5kzgd/)* 

## Peer-reviewed journal articles
<p style="text-align:justify;">
+ Tisdall, L., Mugume, S., Kellen, D., & Mata, R. (2023). Lifespan trajectories of risk preference, impulsivity, and self-control: A dataset containing self-report, informant-report, behavioral, hormone and functional neuroimaging measures from a cross-sectional human sample. _Data in Brief_, 109968. *[Paper](https://www.sciencedirect.com/science/article/pii/S235234092300999X)* 
+ Tisdall, L., & Mata, R. (2023). Age differences in the neural basis of decision-making under uncertainty. _Cognitive, Affective, & Behavioral Neuroscience_, doi: 10.3758/s13415-022-01060-6. *[Paper](https://doi.org/10.3758/s13415-022-01060-6)* 
+ Bagaïni, A., Liu, Y., Bajrami, A., Son, G., Tisdall, L., & Mata, R. (2023). Aging and Economic Preferences: Cumulative meta-analyses of age differences in risk, time, social, and effort preferences. _The Journals of Gerontology: Series B_, gbad034. *[Paper](https://doi.org/10.1093/geronb/gbad034)* 
+ Tisdall, L., MacNiven, K. H., Padula, C. B., Leong, J. K., & Knutson, B. (2022). Brain tract structure predicts relapse to stimulant drug use. _Proceedings of the National Academy of Sciences, 119_(26), e2116703119. *[Paper](https://www.pnas.org/doi/10.1073/pnas.2116703119)* 
+ Tisdall, L., Frey, R., Horn, A., Ostwald, D., Horvath, L., Pedroni, A., ... & Mata, R. (2020). Brain–behavior associations for risk taking depend on the measures used to capture individual differences. _Frontiers in Behavioral Neuroscience, 14,_ 194. *[Paper](https://www.frontiersin.org/articles/10.3389/fnbeh.2020.587152/full?&utm_source=Email_to_authors_&utm_medium=Email&utm_content=T1_11.5e1_author&utm_campaign=Email_publication&field=&journalName=Frontiers_in_Behavioral_Neuroscience&id=587152)*
+ Botvinik-Nezer, R., Holzmeister, F., Camerer, C. F., Dreber, A., Huber, J., Johannesson, M., ... & Rieck, J. R. (2020). Variability in the analysis of a single neuroimaging dataset by many teams. _Nature, 582_(7810), 84-88. *[Paper](https://www.nature.com/articles/s41586-020-2314-9?fbclid=IwAR3jkR1Gkraxbig5vbUz0d0_bVOTCzAFGoCmnRQMG5jpcDwiApCjxZHNHrQ)*
+ Mamerow, L., Frey, R., & Mata, R. (2016). Risk taking across the life span: A comparison of self-report and behavioral measures of risk taking. _Psychology and Aging, 31_(7), 711. *[Paper](https://www.researchgate.net/profile/Loreen-Tisdall/publication/308760553_Risk_Taking_Across_the_Life_Span_A_Comparison_of_Self-Report_and_Behavioral_Measures_of_Risk_Taking/links/606ad0f4a6fdccad3f71a8d3/Risk-Taking-Across-the-Life-Span-A-Comparison-of-Self-Report-and-Behavioral-Measures-of-Risk-Taking.pdf)*
+ Yu, J., Mamerow, L., Lei, X., Fang, L., & Mata, R. (2016). Altered value coding in the ventromedial prefrontal cortex in healthy older adults. _Frontiers in Aging Neuroscience, 8,_ 210. *[Paper](https://www.frontiersin.org/articles/10.3389/fnagi.2016.00210/full)*
+ Meshi, D., Mamerow, L., Kirilina, E., Morawetz, C., Margulies, D. S., & Heekeren, H. R. (2016). Sharing self-related information is associated with intrinsic functional connectivity of cortical midline brain regions. _Scientific Reports, 6_(1), 1-11. *[Paper](https://www.nature.com/articles/srep22491)*
+ Ward, P. R., Mamerow, L., Meyer, S., & Verity, F. E. (2015). Researching the social determinants of health using Social Quality Theory: A national survey in Australia. _Epidemiology II–Theory, Research and Practice,_ 97-115. *[Paper](https://www.researchgate.net/profile/Paul-Ward/publication/276921587_Researching_the_social_determinants_of_health_a_national_survey_in_Australia_using_social_quality_theory/links/555bfb3008aec5ac223295fd/Researching-the-social-determinants-of-health-a-national-survey-in-Australia-using-social-quality-theory.pdf)*
+ Meyer, S. B., Mamerow, L., Henderson, J., Taylor, A. W., Coveney, J., & Ward, P. R. (2014). The importance of food issues in society: Results from a national survey in A ustralia. _Nutrition & Dietetics, 71_(2), 108-116. *[Paper](https://onlinelibrary.wiley.com/doi/pdf/10.1111/1747-0080.12076)*
+ Pearce, M., Willis, E., Mamerow, L., Jorgensen, B., & Martin, J. (2014). The prestige of sustainable living: Implications for water use in Australia. _The Geographical Journal, 180_(2), 161-174. *[Paper](https://rgs-ibg.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/geoj.12016)*
+ Ward, P. R., Mamerow, L., & Meyer, S. B. (2014). Interpersonal trust across six Asia-Pacific countries: Testing and extending the ‘high trust society’and ‘low trust society’theory. _PloS one, 9_(4), e95555. *[Paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0095555)*
+ Ward, P. R., Mamerow, L., & Meyer, S. B. (2013). Identifying vulnerable populations using a Social Determinants of Health framework: Analysis of national survey data across six Asia-Pacific countries. _PLoS One, 8_(12), e83000. *[Paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0083000)*
+ Meyer, S. B., Luong, T. C., Mamerow, L., & Ward, P. R. (2013). Inequities in access to healthcare: analysis of national survey data across six Asia-Pacific countries. _BMC health services research, 13_(1), 1-23. *[Paper](https://bmchealthservres.biomedcentral.com/articles/10.1186/1472-6963-13-238)*
+ Willis, E., Pearce, M., Mamerow, L., Jorgensen, B., & Martin, J. (2013). A healthy scepticism towards water in south Australia. _International Journal of Sociology and Social Policy, 33_(5/6), 380-395. *[Paper](https://www.researchgate.net/profile/Bradley-Jorgensen/publication/257027985_A_Healthy_scepticism_towards_water_in_South_Australia/links/55b9524808ae9289a08ffe60/A-Healthy-scepticism-towards-water-in-South-Australia.pdf)*
+ Henderson, J., Mamerow, L., Taylor, A. W., Ward, P. R., Meyer, S. B., & Coveney, J. (2013). The importance placed on the monitoring of food safety and quality by Australian consumers. _Laws, 2_(2), 99-114. *[Paper](https://heinonline.org/HOL/Page?handle=hein.journals/laws2&div=9&g_sent=1&casa_token=&collection=journals)*
+ Willis, E., Pearce, M., Mamerow, L., Jorgensen, B., & Martin, J. (2013). Perceptions of water pricing during a drought: A case study from South Australia. _Water, 5_(1), 197-223. *[Paper](https://www.mdpi.com/2073-4441/5/1/197/pdf)*
+ Meyer, S. B., Mamerow, L., Taylor, A. W., Henderson, J., Ward, P. R., & Coveney, J. (2012). Demographic indicators of trust in federal, state and local government: Implications for Australian health policy makers. _Australian Health Review, 37_(1), 11-18. *[Paper](https://www.researchgate.net/profile/Julie-Henderson-3/publication/232764489_Demographic_indicators_of_trust_in_federal_state_and_local_government_Implications_for_Australian_health_policy_makers/links/0c960527f31fbce040000000/Demographic-indicators-of-trust-in-federal-state-and-local-government-Implications-for-Australian-health-policy-makers.pdf)*
+ Taylor, A. W., Coveney, J., Ward, P. R., Dal Grande, E., Mamerow, L., Henderson, J., & Meyer, S. B. (2012). The Australian Food and Trust Survey: Demographic indicators associated with food safety and quality concerns. _Food Control, 25_(2), 476-483. *[Paper](https://www.sciencedirect.com/science/article/pii/S0956713511004841)*
+ Ward, P. R., Mamerow, L., Henderson, J., Taylor, A. W., Meyer, S. B., & Coveney, J. C. (2012). The social determinants of food purchasing practices: Who chooses price-before-health, taste-before-price or organic foods in Australia? _Food and Nutrition Sciences,3_(4), 461-470. *[Paper](https://www.scirp.org/pdf/FNS20120400005_13657575.pdf)*
+ Coveney, J., Mamerow, L., Taylor, A. W., Henderson, J., Meyer, S., & Ward, P. R. (2012). Comparative examination of trust during times of a food scandal in Europe and Australia. _Food Public Health, 6_(2), 202-12. *[Paper](https://core.ac.uk/download/pdf/14947466.pdf)*
+ Pearce, M., Willis, E., Mamerow, L., Jorgensen, B., & Martin, J. (2012). A rural-urban divide?: Attitudinal differences towards water restrictions in South Australia. _The Australasian Journal of Regional Studies, 18_(3), 392-419. *[Paper](https://www.researchgate.net/profile/Bradley-Jorgensen/publication/257027984_A_rural-urban_divide_Attitudinal_differences_towards_water_restrictions_in_South_Australia/links/55b9532308ae9289a08ffe75/A-rural-urban-divide-Attitudinal-differences-towards-water-restrictions-in-South-Australia.pdf)*

## Book chapters
+ Coveney, J., Henderson, J., Meyer, S., Mamerow, L., Taylor, A., Ward, P., & Wilson, A. (2015). Consumer Trust. _The SAGE Encyclopedia of Food Issues_. SAGE Publications, Inc. *[Chapter](https://www.researchgate.net/profile/Paul-Ward/publication/276921180_Consumer_Trust_in_Food/links/57d8d7cb08ae601b39afb568/Consumer-Trust-in-Food.pdf)*

## Other contributions
+ Johnson, S. D., Bowers, K. J., Gamman, L., Mamerow, L., & Warne, A. (2010). Theft of customers' personal property in cafes and bars. _Problem-Oriented Guides for Police, 60._ *[Booklet](https://www.popcenter.org/sites/default/files/problems/pdfs/cafe_bar_theft.pdf)*


